# Generated by Django 4.2.2 on 2023-11-30 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0014_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='project_description1',
            field=models.TextField(default='YourDefaultHere', max_length=1000),
        ),
        migrations.AddField(
            model_name='resume',
            name='project_tech1',
            field=models.CharField(default='YourDefaultHere', max_length=100),
        ),
        migrations.AddField(
            model_name='resume',
            name='project_title1',
            field=models.CharField(default='YourDefaultHere', max_length=100),
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
